// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH9YgG7W7kTLi8Y6KlL0lfBuS4sCYhLd4',
    appId: '1:9711185463:web:bda9a02ddbbf1767c259b2',
    messagingSenderId: '9711185463',
    projectId: 'cokcok-27bab',
    authDomain: 'cokcok-27bab.firebaseapp.com',
    storageBucket: 'cokcok-27bab.firebasestorage.app',
    measurementId: 'G-TK5TKD5J97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxohH-MKTI_GRh_LDAaE-KOSJUkjyHOoo',
    appId: '1:9711185463:android:75ecd10406dec759c259b2',
    messagingSenderId: '9711185463',
    projectId: 'cokcok-27bab',
    storageBucket: 'cokcok-27bab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxbQYPLlHGDxGaT_kL6Tu3eTDgQ71zQY',
    appId: '1:9711185463:ios:562aa2cae4622d07c259b2',
    messagingSenderId: '9711185463',
    projectId: 'cokcok-27bab',
    storageBucket: 'cokcok-27bab.firebasestorage.app',
    iosBundleId: 'com.example.cokcok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH9YgG7W7kTLi8Y6KlL0lfBuS4sCYhLd4',
    appId: '1:9711185463:web:4d71754b45998d47c259b2',
    messagingSenderId: '9711185463',
    projectId: 'cokcok-27bab',
    authDomain: 'cokcok-27bab.firebaseapp.com',
    storageBucket: 'cokcok-27bab.firebasestorage.app',
    measurementId: 'G-RTYVY43F6L',
  );
}
